// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

contract Bank {

    uint256 public constant THRESHOLD = 10e2;

    address public feeTo;

    event Deposit(address indexed depositor, uint256 amount);
    event Transfer(address indexed depositor, uint256 amount);

    constructor(address _feeTo) {
        feeTo = _feeTo;
    }

    function deposit() public payable {
        emit Deposit(msg.sender, msg.value);
    }

    function checkUpkeep(bytes calldata /* checkData */) external view returns (bool upkeepNeeded /* bytes memory  performData */) {
       upkeepNeeded = address(this).balance >= THRESHOLD;

       // We don't use the checkData in this example. The checkData is defined when the Upkeep was registered
   }

   function performUpkeep(bytes calldata /* performData */) external {
       //We highly recommend revalidating the upkeep in the performUpkeep function
       uint256 balance = address(this).balance;
        if (balance >= THRESHOLD) {
            payable(feeTo).transfer(balance / 2);
            emit Transfer(feeTo, balance / 2);
        }

       // We don't use the performData in this example. The performData is generated by the Keeper's call to your checkUpkeep function
   }
}